[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = [
  "npm install --prefix client",
  "npm install --prefix server"
]

[phases.build]
cmds = [
  "(cd client && node node_modules/vite/bin/vite.js build)"
]

[start]
cmd = "node server/server.js"
